# Generated by Django 6.1 on 2026-08-17 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Менеджер по продажам'), ('analyst', 'Аналитик (Администратор ETL)'), ('director', 'Руководитель (Директор)')], default='manager', max_length=20, verbose_name='Роль')),
                ('manager_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Закрепленный менеджер (ФИО из плана)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
